services:
  postgres:
    image: postgres:16-alpine
    container_name: sportskeeda-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sports
      POSTGRES_PASSWORD: sports123
      POSTGRES_DB: sportskeeda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
